# Generated by Django 4.0.6 on 2022-11-20 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diseasetype', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
                ('specialize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseasetype.diseasetype')),
            ],
            options={
                'unique_together': {('specialize', 'email')},
            },
        ),
    ]
