# Generated by Django 4.0.6 on 2022-11-20 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diseasetype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('diseaseCode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pathogen', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=140)),
                ('disease_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseasetype.diseasetype')),
            ],
        ),
    ]
